openapi: 3.0.3
info:
  title: Movie Review OpenAPI documentation
  description: Documentation of the movie review resources
  version: 0.0.1

paths:
  /users/:
    get:
      tags:
      - "user"
      description: Get the list of manage users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              example:
              - user_id: 12054
                username: test-user-1
                email_address: test-user-1@oulu.fi
                role: BasicUser
              - user_id: 12055
                username: test-user-2
                email_address: test-user-2@oulu.fi
                role: Admin
    post:
      tags:
      - "user"
      description: Create a new user
      responses:
        '201':
          description: The user was created successfully
          headers:
            Location:
              description: URI of the new user
              schema:
                type: string
        '400':
          description: user_id must be integer, username, email_address, password must be string and role must be BasicUser or Admin
        '409':
          description: User already exists
        '415':
          description: Request content type must be JSON
      requestBody:
        description: JSON document that contains basic data for a new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              user_id: 6546
              username: new-test-user-1
              email_address: new-test-user-1@oulu.fi
              password: e19h63
              role: BasicUser

  /users/{user_id}/:
    parameters:
    - $ref: '#/components/parameters/user_id'
    get:
      tags:
      - "user"
      description: Get details of one user by user_id
      responses:
        '200':
          description: Data of single user
          content:
            application/json:
              examples:
                user-example:
                  description: A user that has been created
                  value:
                    user_id: 12054
                    username: test-user-1
                    email_address: test-user-1@oulu.fi
                    role: BasicUser

        '404':
          description: The user was not found
    put:
      tags:
      - "user"
      description: Update a user by user_id
      responses:
        '204':
          description: The user has been deleted
        '409':
          description: The user was not found

    delete:
      tags:
      - "user"
      description: Delete a user by user_id
      responses:
        '204':
          description: The user has been deleted
        '409':
          description: The user was not found
  /users/{user_id}/reviews/:
    parameters:
    - $ref: '#/components/parameters/user_id'
    get:
      tags:
      - "review"
      description: Get the list of a user's reviews by user_id
      responses:
        '200':
          description: List of reviews
          content:
            application/json:
              example:
              - review_id: 6981
                rating: 3
                comment: The movie is ok
                date: 20210322
              - review_id: 6982
                rating: 5
                comment: The movie is great
                date: 20210323

  /movies/:
    get:
      tags:
      - "movie"
      description: Get the list of manage movies
      responses:
        '200':
          description: List of movies
          content:
            application/json:
              example:
              - movie_id: 94238
                title: test-movie-1
                length: 10447
              - movie_id: 94239
                title: test-movie-2
                director: Nolan
                length: 10532
                release_date: 20180627
    post:
      tags:
      - "movie"
      description: Create a new movie
      responses:
        '201':
          description: The movie was created successfully
          headers:
            Location:
              description: URI of the new movie
              schema:
                type: string
        '400':
          description: title, director must be string, movie_id and length must be integer and releas_date must be integer with YYYYMMDD format
        '409':
          description: Movie already exists
        '415':
          description: Request content type must be JSON
      requestBody:
        description: JSON document that contains basic data for a new movie
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
            example:
              title: new-test-movie-1
              director: villeneuve
  /movies/{movie_id}/:
    parameters:
    - $ref: '#/components/parameters/movie_id'
    get:
      tags:
      - "movie"
      description: Get details of one movie by movie_id
      responses:
        '200':
          description: Data of single movie
          content:
            application/json:
              examples:
                movie-example:
                  description: A movie that has been created
                  value:
                    movie_id: 94238
                    title: test-movie-1
                    length: 10447

        '404':
          description: The movie was not found
    put:
      tags:
      - "movie"
      description: Update a movie by movie_id
      responses:
        '204':
          description: The movie has been deleted
        '409':
          description: The movie was not found

    delete:
      tags:
      - "movie"
      description: Delete a movie by movie_id
      responses:
        '204':
          description: The movie has been deleted
        '409':
          description: The movie was not found
  /movies/{movie_id}/reviews/:
    parameters:
    - $ref: '#/components/parameters/movie_id'
    get:
      tags:
      - "review"
      description: Get the list of a movie's reviews by movie_id
      responses:
        '200':
          description: List of reviews by movie_id
          content:
            application/json:
              example:
              - review_id: 5687
                rating: 3
                comment: The movie is ok
                date: 20210322
              - review_id: 5688
                rating: 5
                comment: The movie is great
                date: 20210323
  /movies/{movie_id}/reviews/{review_id}:
    parameters:
    - $ref: '#/components/parameters/movie_id'
    - $ref: '#/components/parameters/review_id'
    get:
      tags:
      - "review"
      description: Get details of one review by movie_id and review_id
      responses:
        '200':
          description: Data of single review
          content:
            application/json:
              examples:
                user-example:
                  description: A review that has been created
                  value:
                    review_id: 5687
                    rating: 3
                    comment: The movie is ok
                    date: 20210322

        '404':
          description: The review was not found
    put:
      tags:
      - "review"
      description: Update a review by review_id
      responses:
        '204':
          description: The review has been deleted
        '409':
          description: The review was not found

    delete:
      tags:
      - "review"
      description: Delete a review by review_id
      responses:
        '204':
          description: The review has been deleted
        '409':
          description: The review was not found

  /categories/:
    get:
      tags:
      - "category"
      description: Get the list of manage categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              example:
              - category_id: 87675
                title: test-category-1
              - category_id: 87676
                title: test-category-2
    post:
      tags:
      - "category"
      description: Create a new category
      responses:
        '201':
          description: The category was created successfully
          headers:
            Location:
              description: URI of the new category
              schema:
                type: string
        '400':
          description: category_id must be integer and title must be string
        '409':
          description: Category already exists
        '415':
          description: Request content type must be JSON
      requestBody:
        description: JSON document that contains basic data for a new category
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
            example:
              category_id: 27521
              title: new-test-category-1
  /categories/{category_id}/:
    parameters:
    - $ref: '#/components/parameters/category_id'
    get:
      tags:
      - "category"
      description: Get details of one category by category_id
      responses:
        '200':
          description: Data of single category
          content:
            application/json:
              examples:
                category-example:
                  description: A category that has been created
                  value:
                    category_id: 87675
                    title: test-category-1

        '404':
          description: The category was not found
    put:
      tags:
      - "category"
      description: Update a category by category_id
      responses:
        '204':
          description: The category has been deleted
        '409':
          description: The category was not found

    delete:
      tags:
      - "category"
      description: Delete a category by category_id
      responses:
        '204':
          description: The category has been deleted
        '409':
          description: The category was not found

components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          description: User's unique id
          type: integer
        username:
          description: User's unique username
          type: string
        email_address:
          description: User's unique email_address
          type: string
        password:
          description: User's password
          type: string
        role:
          description: User's role
          enum: ["BasicUser", "Admin"]
      required:
      - user_id
      - username
      - email_address
      - password
      - role

    Review:
      type: object
      properties:
        review_id:
          description: User's unique id
          type: integer
        rating:
          description: Review's rating (between 1 and 5)
          type: integer
        comment:
          description: Review's comment
          type: string
        date:
          description: Review's date as YYYYMMDD format
          type: integer
      required:
      - review_id
      - rating
      - date

    Movie:
      type: object
      properties:
        movie_id:
          description: User's unique id
          type: integer
        title:
          description: Movie's title
          type: string
        director:
          description: Movie's director
          type: string
        length:
          description: Movie's length
          type: integer
        release_date:
          description: Movie's release date as YYYYMMDD format
          type: integer
      required:
      - movie_id
      - title

    Category:
      type: object
      properties:
        category_id:
          description: User's unique id
          type: integer
        title:
          description: Category's title
          type: string
      required:
      - category_id
      - title

  parameters:
    user_id:
      description: Selected user's unique id
      in: path
      name: user_id
      required: true
      schema:
        type: integer
    movie_id:
      description: Selected movie's unique id
      in: path
      name: movie_id
      required: true
      schema:
        type: integer
    review_id:
      description: Selected review's unique id
      in: path
      name: review_id
      required: true
      schema:
        type: integer
    category_id:
      description: Selected category's unique id
      in: path
      name: category_id
      required: true
      schema:
        type: integer
